[tool.poetry]
package-mode = false
name = "pathos-backend"
version = "0.1.0"
description = ""
authors = ["Joriel Rivas <compsci937@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
fastapi = ">=0.129.0,<0.130.0"
uvicorn = ">=0.40.0,<0.41.0"
httpx = ">=0.28.1,<0.29.0"
pydantic-settings = ">=2.0.0,<3.0.0"
psycopg = {extras = ["binary"], version = "^3.3.3"}
sqlalchemy = ">=2.0.38,<3.0.0"
alembic = ">=1.14.1,<2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.2,<10.0.0"
ruff = ">=0.15.0,<0.16.0"
mypy = ">=1.19.1,<2.0.0"
pytest-cov = ">=7.0.0,<8.0.0"
pre-commit = "^4.5.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=app --cov-branch --cov-report=term-missing --cov-fail-under=90"
