"""Central registry for stable log event identifiers."""

from __future__ import annotations

ALL_EVENT_IDS: set[str] = {
    "alert_rule_evaluated",
    "alert_rule_failed",
    "alert_run_finished",
    "alert_run_lock_not_acquired",
    "alert_run_started",
    "budget_exceeded",
    "config_validation_failed",
    "config_validation_ok",
    "db_config_checked",
    "delivery_disabled",
    "dry_run_enabled",
    "export_generated",
    "export_hash_generated",
    "health_ready_failed",
    "health_ready_ok",
    "http_exception",
    "migration_safety_mismatch",
    "migration_upgrade_completed",
    "migration_upgrade_started",
    "migration_safety_exception",
    "request_complete",
    "retention_cleanup_executed",
    "migration_audit_written",
    "narration_fallback_used",
    "saved_search_runner_complete",
    "alert_run_skipped",
    "telemetry_recorded",
    "telemetry_summary_generated",
    "unhandled_exception",
    "usajobs_config_missing",
    "usajobs_diagnostics_test_completed",
    "usajobs_diagnostics_test_failed",
    "usajobs_diagnostics_test_started",
    "usajobs_request_complete",
    "usajobs_request_start",
    "validation_exception",
    "worker_heartbeat",
    "worker_lock_acquired",
    "worker_lock_released",
    "poison_pill_quarantined",
    "worker_run_ended",
    "worker_run_failed",
    "worker_run_started",
    "worker_startup_failed",
    "worker_startup_ok",
    "worker_paused",
    "worker_resumed",
    "wipe_operation_completed",
}
